import { Dimensions, StyleSheet } from "react-native";

const windowDimensions=Dimensions.get("window")
export default StyleSheet.create({
    conteiner:{
        flex:1,
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"#F26B0F"
    },
    header_image:{
        height:200,
        width:200,
        alignSelf:"center",
        marginBottom:30,
    },
    exit_button:{
        backgroundColor:"white",
        width:100,
        padding:5,
        borderRadius:10,
        borderColor:"red",
        borderWidth:2,
    },
    exit_button_title:{
        textAlign:"center",
        fontWeight:"bold",
        fontSize:20,
        color:"red",
    },
    line:{
        height:3,
        width:windowDimensions.width,
        alignSelf:"center",
        backgroundColor:"white",
        marginBottom:30,
        marginTop:70,
    },
    inner_conteiner:{
        flexDirection:"row",
    },
    students_button:{
        width:325,
        height:120,
        marginBottom:5,
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
        alignItems:"center",
        justifyContent:"center",
        borderWidth:1,
        borderColor:"grey",
        backgroundColor:"#FEFEFE"
    },
    students_button_image:{
        height:70,
        width:70,
    },
    button_title:{
        textAlign:"center",
        fontWeight:"bold",
        marginTop:10,
    },
    junior_button:{
        width:160,
        height:120,
        marginRight:5,
        borderBottomLeftRadius:20,
        alignItems:"center",
        justifyContent:"center",
        borderWidth:1,
        borderColor:"grey",
        backgroundColor:"#FEFEFE"
    },
    rollcall_button_image:{
        height:60,
        width:60,
    },
    senior_button:{
        width:160,
        height:120,
        borderBottomRightRadius:20,
        alignItems:"center",
        justifyContent:"center",
        borderWidth:1,
        borderColor:"grey",
        backgroundColor:"#FEFEFE"
    }
})