import { StyleSheet } from "react-native";

export default StyleSheet.create({
    conteiner:{
        flex:1,
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:"#F26B0F"
    },
    header_image:{
        height:200,
        width:200,
        alignSelf:"center",
        marginBottom:50,
    },
    exit_button:{
        backgroundColor:"red",
        width:150,
        padding:20,
        marginBottom:50,
        borderRadius:10,
    },
    exit_button_title:{
        color:"white",
        textAlign:"center",
    },
    inner_conteiner:{
        flexDirection:"row",
    },
    students_button:{
        width:325,
        height:120,
        marginBottom:5,
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
        alignItems:"center",
        justifyContent:"center",
        borderWidth:2,
        backgroundColor:"#FEFEFE"
    },
    students_button_image:{
        height:70,
        width:70,
    },
    button_title:{
        textAlign:"center",
        fontWeight:"bold",
        marginTop:10,
    },
    junior_button:{
        width:160,
        height:120,
        marginRight:5,
        borderBottomLeftRadius:20,
        alignItems:"center",
        justifyContent:"center",
        borderWidth:2,
        backgroundColor:"#FEFEFE"
    },
    rollcall_button_image:{
        height:60,
        width:60,
    },
    senior_button:{
        width:160,
        height:120,
        borderBottomRightRadius:20,
        alignItems:"center",
        justifyContent:"center",
        borderWidth:2,
        backgroundColor:"#FEFEFE"
    }
})